### ISSUE TITLE
Determine and upload the program we want to experiment with

### ISSUE THREAD

**Issue by mxz297** [StanPlatinum/elf-respect#1]
One of the first step of this research effort is to determine a set of software we want to experiment with. 

We discuss what programs we want to experiment in this issue.

**Comment by StanPlatinum** [comment]
I will upload a gnome data analysis program (using NW algorithm to search similar patients) later...
Let's see if this can be a experimental subject (code for checking).

**Comment by StanPlatinum** [comment]
I have uploaded the nw (NW algorithm implementation in C++) and the nw_sgx (NW algorithm implementation in C inside the enclave where C is supported well). Please check.

**Comment by StanPlatinum** [comment]
sgx nbench, benchmarks in sgx-shield, and some real-world cases (genomic algorithms, credit scoring algorithms, and https server) have been tested in our self-respect system.
